### ISSUE TITLE
Matter server is not the correct version

### ISSUE THREAD

**Issue by olalonde** [home-assistant-libs/python-matter-server#176]
Getting this error when adding the integration to Home Assistant:

<img width="425" alt="Screen Shot 2023-01-21 at 12 25 19 PM" src="https://user-images.githubusercontent.com/416585/213876539-af7e6d23-8963-4b53-b545-5a2becc804ad.png">

**Comment by olalonde** [comment]
Fixed by checking out 1.1.0 tag

**Comment by olalonde** [comment]
I just checked out the  1.1.0 tag in git, didn't edit any file.

**Comment by mmarius623** [comment]
I'm still getting the not correct version error in HA core running in Docker. 
Even when I try tag 1.1.0.

Any solution available?
